In [1]:
# 이미지와 라벨의 수가 맞는지 확인
from glob import glob
img_list = glob('/home/jin/dev_ws/git_ws/yolov3/mydata/data/images/*.png')
label_list = glob('/home/jin/dev_ws/git_ws/yolov3/mydata/data/labels/*.txt')
print(len(img_list), len(label_list))

220 221


In [6]:
# train과 validation 데이터 나누기
from sklearn.model_selection import train_test_split
train_img_list, val_img_list = train_test_split(img_list, test_size = 0.3,
random_state = 200)
print(len(train_img_list), len(val_img_list))

70 30


In [21]:
# 나눈 데이터를 txt파일로 저장
with open('/home/jin/dev_ws/git_ws/yolov3/train2.txt','w') as f:
    f.write('\n'.join(train_img_list)+'\n')
with open('/home/jin/dev_ws/git_ws/yolov3/val2.txt', 'w') as f:
    f.write('\n'.join(val_img_list)+'\n')

In [22]:
!cd /home/jin/dev_ws/git_ws/yolov3
!python3 train.py --img 640 --batch 32 --epochs 100 --data ./data/mydata.yaml --cfg ./models/yolov3-tiny.yaml --weights '' --name yolov3_cl2

train: weights=, cfg=./models/yolov3-tiny.yaml, data=./data/mydata.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=100, batch_size=32, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=yolov3_cl2, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: ⚠️ YOLOv3 is out of date by 2697 commits. Use 'git pull ultralytics master' or 'git clone https://github.com/ultralytics/yolov5' to update.
YOLOv3 🚀 v9.6.0-106-g316c2e37 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5938MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warm

In [7]:
!python3 detect.py --weights ./runs/train/yolov3_dobot/weights/best.pt --source 0 --img 640 --conf-thres 0.5

detect: weights=['./runs/train/yolov3_cl22/weights/best.pt'], source=0, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv3 🚀 v9.6.0-106-g316c2e37 Python-3.10.12 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3060 Laptop GPU, 5938MiB)

Fusing layers... 
yolov3-tiny summary: 38 layers, 8673622 parameters, 0 gradients, 12.9 GFLOPs
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

0: 480x640 1 yellow, 1 green, 2 centers, 164.4ms
0: 480x640 1 yellow, 1 green, 2 centers, 2.4ms
0: 480x640 1 yellow, 1 green, 2 centers, 3.4ms
0: 480x640 1 yellow, 1 green, 2 centers, 2.9ms
0: 480x640 1 yellow, 1 green, 2 centers, 3.0ms
0: 480x640 1 yellow, 1 green, 2

In [3]:
! cd /home/jin/dev_ws/my_yolov3/pose_ArUCo_v2/
! pwd

/home/jin/dev_ws/git_ws/yolov3


In [4]:
# 아루코마커 포즈
! cd /home/jin/dev_ws/my_yolov3/pose_ArUCo_v2/
! pwd
! python3 4_pose_estimation.py --K_Matrix calibration_matrix.npy --D_Coeff distortion_coefficients.npy --type DICT_4X4_100

python3: can't open file '/home/jin/dev_ws/git_ws/yolov3/4_pose_estimation.py': [Errno 2] No such file or directory


In [3]:
import numpy as np
from torch import tensor

# Your list of tensors
tensors = [
    (tensor(18., device='cuda:0'), tensor(286., device='cuda:0'), tensor(146., device='cuda:0'), tensor(406., device='cuda:0')),
    (tensor(61., device='cuda:0'), tensor(333., device='cuda:0'), tensor(91., device='cuda:0'), tensor(363., device='cuda:0')),
    (tensor(449., device='cuda:0'), tensor(297., device='cuda:0'), tensor(572., device='cuda:0'), tensor(414., device='cuda:0')),
    (tensor(286., device='cuda:0'), tensor(360., device='cuda:0'), tensor(319., device='cuda:0'), tensor(392., device='cuda:0')),
    (tensor(498., device='cuda:0'), tensor(344., device='cuda:0'), tensor(527., device='cuda:0'), tensor(373., device='cuda:0')),
    (tensor(239., device='cuda:0'), tensor(311., device='cuda:0'), tensor(367., device='cuda:0'), tensor(435., device='cuda:0'))
]

# Convert the tensors to NumPy arrays
numpy_arrays = []
for tensor_tuple in tensors:
    tensor_array = [t.cpu().numpy() for t in tensor_tuple]  # Extract values and convert to NumPy array
    numpy_arrays.append(tuple(tensor_array))

# Convert the list of tuples to a NumPy array
numpy_array = np.array(numpy_arrays)

# Print the NumPy array
print(numpy_array)

[[ 18. 286. 146. 406.]
 [ 61. 333.  91. 363.]
 [449. 297. 572. 414.]
 [286. 360. 319. 392.]
 [498. 344. 527. 373.]
 [239. 311. 367. 435.]]
